Add organization page
bpetetot/conference-hall-beta pull request #166
Opened 2018-02-26 10:59 UTC by frinyvonnick

Related #164

2018-02-26 14:09 UTC, bpetetot requested changes

2018-02-26 14:09 UTC, bpetetot commented on src/screens/organizer/organization/components/organizationForm/organizationForm.jsx
> +const OrganizationForm = ({ type, ...formProps }) => (
the `type` is useless here, no ?

2018-02-26 14:09 UTC, bpetetot commented on src/screens/organizer/organization/create/organizationCreate.container.js
> +  type: select(store.getState(), 'type'),
here the type is also useless...

2018-02-26 15:29 UTC, bpetetot approved these changes
👌 Perfect ;)

2018-02-26 17:55 UTC, frinyvonnick commented
I forgot to add organization to user organizations list 😢

2018-02-26 18:05 UTC, bpetetot commented
Yes good catch ! I missed it too :P

2018-02-28 20:59 UTC, bpetetot approved these changes

2018-02-28 21:48 UTC, merged