List organizer organizations
bpetetot/conference-hall-beta pull request #172
Opened 2018-02-27 17:39 UTC by frinyvonnick

Related #164

2018-02-28 20:57 UTC, bpetetot requested changes

2018-02-28 20:57 UTC, bpetetot commented on src/store/listeners/reactions/organizations.js
> +})
nice 👍

2018-02-28 20:57 UTC, bpetetot commented on src/store/listeners/reactions/organizations.js
> +import { map } from 'lodash'
Can you do `import map from 'lodash/map'` ? 
With create-react-app I don't have lodash-plugin so tree-shaking is not so good.

2018-02-28 20:57 UTC, bpetetot commented on src/store/listeners/reactions/organizations.js
>    store.dispatch(push('/organizer/organizations'))
You have to add the new organization into the store in order to have it when you go to the route `'/organizer/organizations'`

2018-03-05 11:01 UTC, frinyvonnick commented on src/store/listeners/reactions/organizations.js
>    store.dispatch(push('/organizer/organizations'))
Done in `refactoring/batch-organization-creation`

2018-03-05 11:06 UTC, bpetetot approved these changes

2018-03-05 15:05 UTC, merged