:sparkles: save proposal sorting to route
bpetetot/conference-hall-beta pull request #180
Opened 2018-03-02 22:02 UTC by hgwood

# Behavior before this change

- As an organiser, select an event, then go to "Call for paper" page
- Proposals are listed newest first
- I change the sort order to Highest rating
- I refresh the page
- Proposals are listed newest first

# Behavior after this change

- I change the sort order to Highest rating
- I refresh the page
- Proposals are listed highest rating first

# Detailed behavior

- Changing the sort order in the UI updates the route query parameter `sortOrder` to match
- Loading the proposals route without a query parameter `sortOrder` updates the route to the order set in the app state, unless there is none, in which case the order default to `newest`
- Loading the proposals route with a valid* query parameter `sortOrder` updates the app state to match
- Loading the proposals route with an invalid* query parameter `sortOrder` results in both the route query parameter and the app state getting set to `newest`

* "valid" refers to the value being one of the four values defined in the route config for the route `PROPOSALS`

2018-03-03 20:22 UTC, hgwood commented
I'm having second thoughts about my implementation. There should not be 2 places in the redux state for the same information, there should be only one. Let me try something else.

2018-03-04 22:02 UTC, hgwood commented
I tried to have only the router state carry the sort order, but that had the unforeseen consequences of loosing the sort order when navigating to another route. I don't know if that's a good thing or not but it breaks with the current behavior. What's your opinion?

2018-03-05 09:12 UTC, bpetetot requested changes
Very good work ! Thanks 👍 

And yes, I think we should keep also the current behaviour, to keep sorting by navigating and refreshing. It will give a better experience for the user.

2018-03-05 09:12 UTC, bpetetot commented on src/store/listeners/reactions/router.js
> +      store.dispatch(store.ui.organizer.proposals.update({ sortOrder }))
`store.dispatch` is not necessary with k-ramel redux factories. actions are dispatched automatically by calling the action creator.

2018-03-05 09:41 UTC, hgwood commented on src/store/listeners/reactions/router.js
> +      store.dispatch(store.ui.organizer.proposals.update({ sortOrder }))
Right.

2018-03-05 09:46 UTC, hgwood commented on src/store/listeners/reactions/router.js
> +      store.dispatch(store.ui.organizer.proposals.update({ sortOrder }))
Fixed.

2018-03-05 10:02 UTC, bpetetot approved these changes

2018-03-05 15:54 UTC, merged