Add member in organization
bpetetot/conference-hall-beta pull request #184
Opened 2018-03-05 19:27 UTC by frinyvonnick

Related #164

2018-03-05 21:59 UTC, bpetetot requested changes
nice work ;)

2018-03-05 21:59 UTC, bpetetot commented on src/store/listeners/reactions/user.js
> +  store.data.organizations.update(splice(organization, 'users', userIndex, 1))
may be easier to read using a filter ?

```js
const organization = store.data.organizations.get(organizationId)
store.data.organizations.update(filter(organization, 'users',  u => u.uid !== uid))
```

2018-03-05 21:59 UTC, bpetetot commented on src/components/addUser/addUserButton.jsx
> +      </a>
use default button with iconLabel as default 

```jsx
<button className="btn" onClick={openModal}>
  <IconLabel icon={icon} label={label} />
</button>
```

2018-03-05 21:59 UTC, bpetetot commented on src/components/addUser/addUserButton.jsx
> +    {children ? children({ openModal }) : (
May be with with a `render as props` than `function as children` pattern should be better to implement.

**With function as children :**
```jsx
<AddUserButton ...>
  {openModal => <button onClick={openModal} />}
</AddUserButton>
```

**With render as props :**
```jsx
<AddUserButton ... renderButton={openModal => <button onClick={openModal} />} />
```

2018-03-05 21:59 UTC, bpetetot commented on src/components/addUser/addUserButton.jsx
> +  modalId: PropTypes.string.isRequired,
I think `modalId` could be in the `modalOptions` object

2018-03-07 15:47 UTC, bpetetot commented on src/screens/components/talk/speakers/addSpeaker/addSpeakerButton.container.js
> +  const url = window.location.href.split('/')
I think we will need to extract this kind of work in a utility function, because I'm doing the same thing in an other component. But It's may be not the purpose of this PR, this may need a dedicated issue. What do you think about it ?

2018-03-07 15:47 UTC, bpetetot approved these changes

2018-03-07 15:48 UTC, bpetetot commented
Don't forget, there is an other step to implement : 
> manage the invitation step

_Maybe in an other PR_

2018-03-07 17:21 UTC, frinyvonnick commented
I manage invitation link in #0fd68d2

2018-03-07 17:43 UTC, frinyvonnick commented on src/components/addUser/addUserButton.jsx
> +    {children ? children({ openModal }) : (
Didn't know why it was better. Found this http://americanexpress.io/faccs-are-an-antipattern/

2018-03-07 18:13 UTC, frinyvonnick commented on src/components/addUser/addUserButton.jsx
> +  modalId: PropTypes.string.isRequired,
I need it for the `withModal()` hoc. I used recompose and `withProps()` hoc to handle it. What do you think about it ?

2018-03-07 18:15 UTC, frinyvonnick commented on src/screens/components/talk/speakers/addSpeaker/addSpeakerButton.container.js
> +  const url = window.location.href.split('/')
Good idea, it will be easier to refactor it in another PR 👍

2018-03-08 09:01 UTC, bpetetot reviewed
Yeah ! great work !
I have added some comments about labels and prop-types. Once you have done it, you can merge directly

2018-03-08 09:01 UTC, bpetetot commented on src/components/addUser/addUserButton.jsx
> +  label: 'Add a user',
Change the label with "Add a member"

2018-03-08 09:01 UTC, bpetetot commented on src/components/addUser/addUserModal.jsx
> +  title: 'Add a user',
Change label with 'Add a member'

2018-03-08 09:01 UTC, bpetetot commented on src/screens/organizer/organization/page/organizationPage.jsx
> +      address.
Change the word 'organizer' by 'member' in the 2 paragraphs

2018-03-08 09:01 UTC, bpetetot commented on src/screens/organizer/inviteOrganizer/inviteOrganizer.jsx
> +      <p>You&apos;re will be able to update it and invite users.</p>
change `You're will be able to update it and invite users` by `You're will be able to update it and invite members`

2018-03-08 09:01 UTC, bpetetot commented on src/components/addUser/addUserButton.jsx
>    modalOptions: PropTypes.shape({
`message` and `resultsMessage` prop types are `PropTypes.node.isRequired` instead of `PropTypes.string.isRequired`

2018-03-08 12:55 UTC, frinyvonnick commented on src/components/addUser/addUserButton.jsx
>    modalOptions: PropTypes.shape({
message is a `node` as you can see here https://github.com/bpetetot/conference-hall/pull/184/files/ad81cc04e0b17b3cf8eac61ededef92043f91dc4#diff-a2169d98bd0e039c81c022a5fa699213R11

2018-03-16 07:42 UTC, fabienjuif commented on src/screens/components/talk/speakers/addSpeaker/addSpeakerButton.container.js
> +  const url = window.location.href.split('/')
I think this is one purpose of redux-little-router no ?

2018-03-16 07:43 UTC, fabienjuif commented on src/components/addUser/addUserModal.jsx
> +    {!searching && (
`searching ||`

2018-03-16 07:47 UTC, fabienjuif commented on src/screens/organizer/inviteOrganizer/inviteOrganizer.container.js
> +      store.dispatch({ type: '@@ui/ON_LOAD_ORGANIZATION', payload: organizationId })
k-ramel is more about
 - 1 event per callback
 - Then use reactions to do what you want to do

You can use `listen` hoc to bind listeners to a component. And then you have an init event on mount `@@krml/LISTENERS>ADDED>${name}` or something like that.
(If you want to try)

2018-03-16 07:48 UTC, fabienjuif commented on src/screens/organizer/inviteOrganizer/inviteOrganizer.container.js
> +import { push } from 'redux-little-router'
You already have the driver from k-ramel for doing that.
You can either use it in inject :  `inject((store, ownProps, drivers) => {})`
Either use it in a reaction (which is better since we should have 1 event/dispatch, per callback): `(action, store, drivers)`

2018-03-16 07:49 UTC, fabienjuif commented on src/screens/organizer/organization/page/organizationPage.container.js
>      loaded: !!organization && !!organization.users,
You still prefer doing that instead of configuring `hoc-react-loader` ?

`loader({ print: ['users'] })`

2018-03-31 15:50 UTC, frinyvonnick commented on src/components/addUser/addUserModal.jsx
> +    {!searching && (
finally, I used a ternary operator 😄

2018-03-31 15:57 UTC, frinyvonnick commented on src/screens/organizer/inviteOrganizer/inviteOrganizer.container.js
> +      store.dispatch({ type: '@@ui/ON_LOAD_ORGANIZATION', payload: organizationId })
Do you have some example ?

2018-04-01 17:25 UTC, fabienjuif commented on src/screens/organizer/inviteOrganizer/inviteOrganizer.container.js
> +      store.dispatch({ type: '@@ui/ON_LOAD_ORGANIZATION', payload: organizationId })
You can see an example here : https://github.com/alakarteio/k-todomvc/pull/13
:)

2018-04-02 12:34 UTC, bpetetot approved these changes
👌

2018-04-03 06:01 UTC, merged