:sparkles: all proposals filters saved in route
bpetetot/conference-hall-beta pull request #187
Opened 2018-03-07 22:21 UTC by hgwood

This is a follow up to #180 and step 1 towards fixing #178 (see https://github.com/bpetetot/conference-hall/issues/178#issuecomment-370376745). Behavior is the same as described in #180.

2018-03-08 09:32 UTC, bpetetot requested changes

2018-03-08 09:32 UTC, bpetetot commented on src/store/listeners/reactions/proposals.js
> +    pickBy(filter => filter),
I think you can directly do `pickBy()` as the default iteratee is `_.identity`

2018-03-08 09:32 UTC, bpetetot commented on src/store/listeners/reactions/proposals.js
> +    filters => Object.assign(filters, addedOrModifiedFilters),
maybe with spread operator ?
```js
filters => ({ ...filters, ...addedOrModifiedFilters})
```

2018-03-08 09:32 UTC, bpetetot commented on src/store/listeners/reactions/proposals.js
> +    flow(pickBy(filter => !filter), Object.keys),
You can also use `_.isEmpty` : 
```js
flow(pickBy(isEmpty), Object.keys),
```

2018-03-08 09:32 UTC, bpetetot commented on src/store/listeners/reactions/router.js
> +    const pickTruthyValues = pickBy(Boolean)
I think in that case, just a `pickBy()` function (identity) is needed

2018-03-08 10:37 UTC, hgwood commented on src/store/listeners/reactions/proposals.js
> +    pickBy(filter => filter),
I'd like to communicate that this iteratee is the negation of the one above. Still want to change it?

2018-03-08 10:44 UTC, bpetetot commented on src/store/listeners/reactions/proposals.js
> +    pickBy(filter => filter),
You're right it's more understandable, keep it that way

2018-03-08 11:16 UTC, hgwood commented on src/store/listeners/reactions/proposals.js
> +    filters => Object.assign(filters, addedOrModifiedFilters),
Right. That's better.

2018-03-08 11:17 UTC, hgwood commented on src/store/listeners/reactions/router.js
> +    const pickTruthyValues = pickBy(Boolean)
Right.

2018-03-08 20:45 UTC, hgwood commented on src/store/listeners/reactions/router.js
> +    const pickTruthyValues = pickBy(Boolean)
Actually, that only works in "classic" lodash. Lodash/fp does not have default values for parameters because of currying.

2018-03-12 10:03 UTC, bpetetot approved these changes
👌

2018-03-12 13:45 UTC, merged

2018-03-12 13:45 UTC, bpetetot commented
It's merged, thanks @hgwood