:sparkles:  modify your own commentary in the Organizers Thread
bpetetot/conference-hall-beta pull request #525
Opened 2019-04-05 14:29 UTC by antoinecellier

2019-04-05 16:14 UTC, bpetetot requested changes
Great job, thanks 🙏but when I test it I have a little bug 🐛
When I want to add a new message, the last one is overrided: 
https://www.useloom.com/share/429268c5455b48d8b81068a2ca1c9886

2019-04-05 16:14 UTC, bpetetot commented on src/components/thread/message.jsx
> +  const [inputMessageValue, setInputMessageValue] = useState(message)
❤️

2019-04-05 16:14 UTC, bpetetot commented on src/components/thread/message.jsx
> +    }
Can you also add "Escape" key to cancel ?

2019-04-05 16:14 UTC, bpetetot commented on src/components/thread/message.jsx
> +    onEdit(id)
Why do you manage "editable" state outside the component (in redux state), I think you could manage it completely inside it (with a state) ?

2019-04-05 16:14 UTC, bpetetot commented on src/components/thread/message.jsx
> +            {modified && ' ( modified )'}
Remove space between the word and '(' ')' : `(modified)`

2019-04-05 16:14 UTC, bpetetot commented on src/components/thread/message.module.css
> +  width: 21em;
Can you change the style of the message edit and doing something like that ? 😛

![image](https://user-images.githubusercontent.com/516360/55641418-307eb300-57ce-11e9-8c1c-5899c1b542be.png)

2019-04-05 18:23 UTC, antoinecellier commented on src/components/thread/message.jsx
> +    }
Hmm, I have some difficulties to stop propagation of `escape` event. If I press escape key organizers thread closes :/

I try
```
if (event.keyCode === 27) {
      event.preventDefault()
      event.stopPropagation()
      onCancel()
    }
```

without success ....

2019-04-08 20:27 UTC, bpetetot reviewed
Some little changes, then it will be perfect ;)

2019-04-08 20:27 UTC, bpetetot commented on src/components/thread/message.jsx
> +      onSave(inputMessageValue, id)
call `this.handleSave(inputMessageValue, id)` instead of `onSave(inputMessageValue, id)` to automatically close the editable textbox when saved.

2019-04-08 20:27 UTC, bpetetot commented on src/components/thread/message.module.css
> +  border-bottom-left-radius: 0;
can you remove `border-top-left-radius` and  `border-bottom-left-radius` ?

2019-04-08 20:27 UTC, bpetetot commented on src/components/thread/message.module.css
> +  border-bottom-right-radius: 0;
can you remove `border-top-right-radius` and  `border-bottom-right-radius` ?

2019-04-08 20:27 UTC, bpetetot commented on src/components/thread/message.jsx
> +          <Button onClick={handleSave}>Save changes</Button>
Can you just set "Save" as label to the button ?

2019-04-08 20:41 UTC, bpetetot approved these changes

2019-04-08 20:42 UTC, merged

2019-04-08 20:43 UTC, bpetetot commented
Merged! Thanks @antoinecellier